version: 2

## Customize the test machine
jobs:
  build:
    working_directory: ~/bitrefill/airfill-widget
    environment:
      NODE_ENV: test
    docker:
      - image: circleci/node:8.11.3-jessie
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run test builds
          command: yarn build
